server:
  port: 1200

spring:
  application:
    name: "book-store"
  profiles:
    active: qa 

  datasource:
    url: "jdbc:mysql://localhost/sb_july"
    username: "root"
    password: "root"

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    com.ashu.book_store.service: DEBUG

upload:
  file:
    dir: "images"
